Brainwave/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from idea import views

from contacts.views import contact_view, status_view, about_view


urlpatterns = [
    path('ideas/', include('idea.urls', namespace='ideas')),
    path('', views.index, name='index'),
    path('categories/', include('category.urls', namespace='categories')),
    path('comments/', include('comment.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path('users/', include('user.urls', namespace='users')),
    path("contacts/", contact_view, name='contact_us'),
    path("about/", about_view, name='about'),
    path("status/<str:task_id>/", status_view),
    path('partnership/', include('partnership.urls', namespace='partnership')),
    path('investments/', include('investment.urls', namespace='investments')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('direct/', include('direct.urls', namespace='directmessages'))
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

idea/urls.py
from django.urls import path
from idea import views
from comment import views as comment_views

app_name = 'ideas'

urlpatterns = [
    path('list/', views.IdeasListView.as_view(), name='list'),
    path('idea/<int:pk>', views.IdeasDetailView.as_view(), name='detail'),
    path('create/', views.IdeasCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.IdeasUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.IdeasDeleteView.as_view(), name='delete'),
    path('idea/<int:pk>/comment/add/', comment_views.CommentCreateView.as_view(), name='add_comment'),
    path('idea/<int:pk>/comment/edit/<int:comment_pk>/', comment_views.CommentUpdateView.as_view(), name='edit_comment'),
    path('idea/<int:pk>/comment/delete/<int:comment_pk>/', comment_views.CommentDeleteView.as_view(), name='delete_comment'),
    path('idea/<int:pk>/add_likes/', views.AddLike.as_view(), name='add_likes'),
    path('idea/<int:pk>/add_dislikes/', views.DisLike.as_view(), name='add_dislikes'),
    path('list/filter/', views.IdeasFilter.as_view(), name='ideas-filter'),
    path('idea/<int:pk>/favourites/', views.FavouriteIdeaView.as_view(), name='favourite'),
    path('idea/<int:pk>/favourites/delete/', views.FavouriteDeleteView.as_view(), name='favourite_delete'),
]

partnership/urls.py
from django.urls import path
from partnership import views


app_name = 'partnership'

urlpatterns = [
    path('', views.CoAuthorsView.as_view(), name='list'),
    path('create/<int:pk>', views.PreCoAuthorView.as_view(), name='pre_coauthor_create'),
    path('approve/<int:notification_id>', views.ApproveCoAuthor.as_view(), name='approve_coauthor'),
    path('reject/<int:notification_id>', views.RejectCoAuthor.as_view(), name='reject_coauthor'),
    path('delete/<int:pk>', views.PreCoAuthorDeleteView.as_view(), name='pre_coauthor_delete'),
    path('stop_being_coauthor/<int:pk>', views.StopBeingCoAuthor.as_view(), name='stop_being_coauthor'),
]

user/urls.py
from django.urls import path
from user import views


app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.AuthView.as_view(), name='login'),
    path('logout/', views.ExitView.as_view(), name='logout'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('profile/<int:pk>/', views.UserProfile.as_view(), name='profile'),
    path('profile/<int:pk>/ideas/', views.UserIdeas.as_view(), name='user_ideas'),
    path('profile/<int:pk>/following/', views.FollowUser.as_view(), name='following'),
    path('profile/<int:pk>/followers/', views.Followers.as_view(), name='followers'),
    path('profile/<int:pk>/partnerships/', views.UserCoAuthorIdeas.as_view(), name='partnerships'),
    path('profile/<int:pk>/favourites/', views.UserFavouritesIdeas.as_view(), name='favourites'),
    path('profile/<int:pk>/investments/', views.UserInvestmentIdeas.as_view(), name='investments'),
]

idea/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete

from notifications.models import Notification
from user.models import Follow



class Idea(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    category = models.ForeignKey('category.Category', on_delete=models.CASCADE)
    author = models.ForeignKey('user.User', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='idea_images/', default='idea_images/no_idea.jpg')
    status = models.ForeignKey("IdeaStatus", on_delete=models.CASCADE, default=1)
    co_author = models.ManyToManyField('user.User', through='partnership.CoAuthor', related_name='coauthored_ideas', blank=True)
    investors = models.ManyToManyField('user.User', through='investment.Investor', related_name='investors_ideas', blank=True)


# class IdeaImages(models.Model):
#     idea = models.ForeignKey(Idea, related_name='images', on_delete=models.CASCADE)
#     image2 = models.ImageField(upload_to='idea_images/', default='idea_images/no_idea.jpg')

    def __str__(self):
        return (f"{self.title}/{self.category}/{self.author}")

    def comments_count(self):
        return self.comments.count()

    def idea_follow(sender, instance, created, **kwargs):
        if created:
            idea = instance
            followers = idea.author.follower.all()
            for follow in followers:
                # print(f"Follower: {follow.following.username}")
                notify = Notification(idea=idea, sender=idea.author, user=follow.following, notification_type=9)
                notify.save()
    def idea_follow_delete(sender, instance, **kwargs):
            idea = instance
            followers = idea.author.follower.all()
            for follow in followers:
                notifications = Notification.objects.filter(idea=idea, sender=idea.author, user=follow.following, notification_type=9)
                notifications.delete()



class Likes(models.Model):

    idea = models.ForeignKey(Idea, verbose_name='Idea', on_delete=models.CASCADE)
    author = models.ForeignKey('user.User', verbose_name='User', on_delete=models.CASCADE)

    def user_liked_idea(sender, instance, *args, **kwargs):
        like = instance
        idea = like.idea
        sender = like.author
        notify = Notification(idea=idea, sender=sender, user=idea.author, notification_type=1)
        notify.save()

    def user_unlike_idea(sender, instance, *args, **kwargs):
        like = instance
        idea = like.idea
        sender = like.author

        notify = Notification.objects.filter(idea=idea, sender=sender, notification_type=1)
        notify.delete()



class DisLikes(models.Model):

    idea = models.ForeignKey(Idea, verbose_name='Idea', on_delete=models.CASCADE)
    author = models.ForeignKey('user.User', verbose_name='User', on_delete=models.CASCADE)

    def user_disliked_idea(sender, instance, *args, **kwargs):
        dislike = instance
        idea = dislike.idea
        sender = dislike.author
        notify = Notification(idea=idea, sender=sender, user=idea.author, notification_type=2)
        notify.save()

    def user_undislike_idea(sender, instance, *args, **kwargs):
        dislike = instance
        idea = dislike.idea
        sender = dislike.author

        notify = Notification.objects.filter(idea=idea, sender=sender, notification_type=2)
        notify.delete()


class IdeaStatus(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('pending', 'Pending'),
        ('completed', 'Completed'),
    ]

    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    updated_by = models.ForeignKey('user.User', on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.status

class Favourite(models.Model):
    idea = models.ForeignKey(Idea, verbose_name='Idea', on_delete=models.CASCADE, related_name='favourite')
    user = models.ForeignKey('user.User', verbose_name='User', on_delete=models.CASCADE, related_name='user')


# Likes
post_save.connect(Likes.user_liked_idea, sender=Likes)
post_delete.connect(Likes.user_unlike_idea, sender=Likes)
# DisLikes
post_save.connect(DisLikes.user_disliked_idea, sender=DisLikes)
post_delete.connect(DisLikes.user_undislike_idea, sender=DisLikes)
# Idea Follow
post_save.connect(Idea.idea_follow, sender=Idea)
post_delete.connect(Idea.idea_follow_delete, sender=Idea)

idea/forms.py
from django import forms
from .models import Idea
from common_imports.validation import category_import, user_import

class IdeasForm(forms.ModelForm):

    Category = category_import()
    User = user_import()

    class Meta:
        model = Idea
        fields = ('title', 'description', 'category', 'image')

    title = forms.CharField(
        label='Idea Title',
        # initial='New Idea',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Input Idea',
                'class': 'form-control',
            }
        )
    )
    description = forms.CharField(
        label='Description',
        # initial='Idea description',
        required=False,
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Input Description here',
            }
        )
    )

    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label='Select category',
    )

    image = forms.ImageField(
        label='Image',
        required=False,
    )


    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)
        super(IdeasForm, self).__init__(*args, **kwargs)
        if request:
            self.fields['author'].initial = request.user
            self.fields['author'].widget = forms.HiddenInput()

idea/templates/ideas/idea_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete {{ object.name }} ???
{%  endblock %}

{% block body %}

    <h1>{{ object.title }}</h1>
    <h2>Description: {{ object.description }}</h2>
    <h2>Category: {{ object.category }}</h2>
    <h3>Author: {{ object.author }}</h3>
    <h3>Created at: {{ object.created_at }}</h3>


Do you confirm the deletion?
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes</button>
    <button type="button" onclick="handleNoClick()">No</button>
</form>

    <script>
        function handleNoClick() {
            window.location.href = '{% url 'ideas:list' %}';
        }
    </script>


<a href="{% url 'ideas:list' %}">Back to the Idea list</a>

{% endblock %}

idea/templates/ideas/idea_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.name }}
{%  endblock %}

{% block body %}

<style>
.fav-button {
    text-decoration: none;
    color: #555;
    font-size: 24px;
    display: flex;
    align-items: center;
    position: relative;
    margin: 0 5px;
    transition: color 0.3s;
}

.fav-button:hover {
    color: #1e9a03;
}

.fav-icon {
    position: relative;
    font-size: 20px;
    transition: transform 0.3s;
}

.fav-button:hover .fav-icon {
    transform: scale(1.2);
}

.fav-count {
    position: absolute;
    top: -4px;
    right: -8px;
    background-color: #1e9a03;
    color: white;
    border-radius: 50%;
    padding: 2px 6px;
    font-size: 8px;
    font-weight: bold;
    transition: background-color 0.3s;
}

.fav-button:hover .fav-count {
    background-color: #1e9a03;
}


/*
=========================
Idea Cards
=========================
*/

:root {
  --indent: 0;
}

@media screen and (min-width: 40rem) {
  :root {
    --indent: clamp(1.5rem, 4vw, 2.5rem);
  }
}


.wrapper {
    display: flex;
    flex-direction: column;
    align-items: flex-end;
}

.cardb {
  margin: 2rem;
  display: grid;
    transform: scale(0.75);
    transform-origin: center;
  grid-template-columns:
    var(--indent) calc(3 * var(--indent)) 1fr 1fr calc(2 * var(--indent))
    var(--indent);
  grid-template-rows:
    var(--indent) calc(3 * var(--indent)) 1fr calc(2 * var(--indent))
    var(--indent);
  max-width: 80rem;
}

.cardb::before {
  content: "";
  display: block;
  background: #c9efe0;
  background-size: cover;
  grid-column: 2/-1;
  grid-row: 2/-1;
  box-shadow: 0 0 2rem hsla(232, 100%, 50%, 0.35);
}

.cardb::after {
  content: "";
  display: block;
  background: #639584;
  grid-column: 1/-2;
  grid-row: 1/-2;
  z-index: -1;
}

.cardb img {
  grid-column: 4/5;
  grid-row: 3/4;
  box-shadow: 0 0 1rem hsla(221, 96%, 55%, 0.95);
  object-fit: cover;
  aspect-ratio: 1 / 1;
}

.cardb figcaption {
  grid-column: 3/5;
  grid-row: 3/4;
  display: grid;
  grid-template-columns: 3fr 1fr 2fr;
}

.cardb blockquote {
  grid-column: 1/3;
  margin: 0;
  padding-bottom: 1rem;
  font-size: 3rem;
  font-weight: 100;
  align-self: flex-end;
}

.cardb cite {
  grid-column: 1/2;
  font-size: 1.3rem;
  font-weight: 100;
  font-style: normal;
}

.cardb .credit {
  grid-column: 2/4;
  place-self: flex-end;
  margin: 0;
  padding: 1rem;
  text-align: end;
  color: #ea1616;
  font-weight: 400;
}

.cardb a {
  color: #e82929;
}

</style>

    {% if user.is_authenticated and user.id == idea.author.id or user.is_staff %}
        <div class="mb-3">
            <a href="{% url 'ideas:update' pk=idea.id %}" class="btn btn-primary">
                Update
            </a>
            <a href="{% url 'ideas:delete' pk=idea.id %}" class="btn btn-danger">
                Delete
            </a>
        </div>
    {% endif %}

<div class="container">
    <div class="row">
        <!-- Первый элемент сетки -->
        <div class="col-10 col-sm-12 col-md-10 col-lg-8 col-xl-6 col-xxl-6">
            <div class="wrapper" style="margin-bottom: -60px; margin-top: -90px; margin-right: -140px;">
                <figure class="cardb">
                    <img src="{{ idea.image.url }}" width="640" height="400" alt="idea_image"/>
                    <figcaption>
                        <h5 style="color: #5e5e5e; font-size: 30px;">{{ idea.title }}</h5>
                        <blockquote style="color: #5e5e5e; font-size: 30px;"></blockquote>
                        <cite></cite>
                        <p class="credit">
                            <strong><a style="font-size: 20px;" href="{% url 'users:profile' pk=idea.author.pk %}">{{ idea.author }}</a></strong>, {{ idea.created_at }}
                        </p>
                    </figcaption>
                </figure>
            </div>

                <div class="like-dislike-container">
                    <a href="{% url 'ideas:add_likes' idea.id %}" class="like-button">
                        <span class="like-icon" data-bs-toggle="tooltip" data-bs-placement="top" title="
                                {{ check_like }}
                        ">
                            <img src="/media/social_media/like.png" width="35px" height="35px">
                            <span class="like-count">{{ idea.likes_set.all.count }}</span>
                        </span>
                    </a>
                    <a href="{% url 'ideas:add_dislikes' idea.id %}" class="dislike-button" data-bs-toggle="tooltip" data-bs-placement="top" title="
                                {{ check_dislike }}
                        ">
                        <span class="dislike-icon">
                            <img src="/media/social_media/dislike.png" width="35px" height="35px">
                            <span class="dislike-count">{{ idea.dislikes_set.all.count }}</span>
                        </span>
                    </a>
                    <a href="{% url 'ideas:favourite' idea.id %}" class="fav-button">
                        <span class="fav-icon" data-bs-toggle="tooltip" data-bs-placement="top" title="
                                {{ check_favourite }}
                        ">
                            <img src="/media/social_media/favourite.png" width="35px" height="35px">
                            <span class="fav-count">{{ idea.favourite.all.count }}</span>
                        </span>
                    </a>
                </div>

                <div class="container">
                    <br>
                    <p>Idea Status:
                        {% if idea.status.status == 'active' %}
                            <span class="badge rounded-pill text-bg-primary">{{ idea.status.status }}</span>
                        {% elif idea.status.status == 'pending' %}
                            <span class="badge rounded-pill text-bg-warning">{{ idea.status.status }}</span>
                        {% elif idea.status.status == 'completed' %}
                            <span class="badge rounded-pill text-bg-success">{{ idea.status.status }}</span>
                        {% else %}
                            <span class="badge rounded-pill text-bg-secondary">No status</span>
                        {% endif %}
                    </p>
                    <hr>

                    <a href="#">Rating</a>
                    <hr>

                    <a href="#">Share</a>
                    <hr>
                    <div>
                        {% if user.is_authenticated and request.user.id != idea.author.id %}
                            {% if is_pre_coauthor %}
                                <p>☑️ Your Co-Author request was sent successfully. Please, waiting for approval</p>
                                  <form method="post" action="{% url 'partnership:pre_coauthor_delete' precoauthor_id %}">
                                      {% csrf_token %}
                                      <button type="submit" class="btn btn-danger">Cancel my request</button>
                                  </form>


                                <br>
                            {% elif is_coauthor %}
                                <p>✅ You are Co-Author of this Idea</p>
                                <form method="post" action="{% url 'partnership:stop_being_coauthor' pk=idea.pk %}?next=ideas:detail">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-warning mb-5">Stop being Co-Author</button>
                                </form>
                            {% else %}
                                <a href="#" data-toggle="modal" data-target="#confirmModal">Become co-author</a>
                            {% endif %}
                        {% endif %}
                    </div>


                    <!-- Модальное окно подтверждения стать со-автором -->
                    <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="confirmModalLabel" style="color: black">Confirmation</h5>
                                </div>
                                <div class="modal-body">
                                    <p style="color: black">Are you sure you want to be a co-author of this Idea?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                    <form method="post" action="{% url 'partnership:pre_coauthor_create' pk=idea.pk %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-primary">Send request</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>



                    <small>Co-Authors:
                        <ul>
                        {% for co_author in idea.coauthor_set.all %}
                            <li>User: {{ co_author.user.username }}</li>
                            <li>Role: {{ co_author.role }}</li>
                            <li>Joined: {{ co_author.joined_at }}</li>
                            <br>
                            <br>
                        {% endfor %}
                        </ul>
                    </small>
                    <hr>

                    <a href="#">Invest to this Idea</a>
                    <div>
                        <small>Investors:
                            <ul>
                            {% for investor in idea.investor_set.all %}
                                <li>User: {{ investor.user.username }}</li>
                                <li>Status: {{ investor.status }}</li>
                                <li>Investment amount: {{ investor.amount_invested }}$</li>
                                <li>Investment Type: {{ investor.investment_type }}</li>
                                <li>Joined: {{ investor.joined_at }}</li>
                                <li>Note: {{ investor.note }}</li>
                            {% endfor %}
                            </ul>
                        </small>
                    </div>
                    <hr>
                </div>

            <div class="mt-4">
                <a href="{% url 'ideas:list' %}">Back to the Idea list</a>
            </div>
        </div>

        <!-- Второй элемент сетки -->
       <div class="col-10 col-sm-12 col-md-12 col-lg-12 col-xl-6 col-xxl-6">
            <div class="border p-3">
                {% include "components/comment.html" with idea=idea comments=idea.comments.all %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

idea/templates/ideas/idea_form.html
{% extends 'base.html' %}

{% block title %}
    Create Idea
{%  endblock %}

{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="submit" class="button56">Create</button>
    </div>
</form>

<br>
<a href="{% url 'ideas:list' %}">Back to the Idea list</a>

{% endblock %}

idea/templates/ideas/idea_update_form.html
{% extends 'base.html' %}

{% block title %}
    Idea Update
{%  endblock %}

{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Update</button>
</form>

<br>
<a href="{% url 'ideas:list' %}">Back to the Idea list</a>

{% endblock %}

idea/templates/ideas/list.html
{% extends 'base.html' %}

{% block title %}
    Ideas
{%  endblock %}

{% block body %}

<style>

.fixed-size-card {
    width: 100%;
    height: 600px;
}

.fixed-size-img {
    width: 100%;
    height: 300px;
    object-fit: cover;
}

.bg-blue {
    background-color: #e8fbf3;
}

.card {
    border: none;
}

.card-title, .card-text {
    color: #000000;
}

</style>

    <div class="text-center">
        <h1>Join someone's Idea or
            <a href="{% url 'ideas:create' %}" style="text-decoration: none; color: #e8fbf3;">Create your own</a>
        </h1>
    </div>

    <div class="row row-cols-1 row-cols-md-3 g-5 my-1">
        {% for idea in object_list %}
            <div class="col">
                <a href="{% url 'ideas:detail' pk=idea.id %}" class="text-decoration-none">
                    <div class="card h-100 bg-blue fixed-size-card">
                        <img src="{{ idea.image.url }}" class="card-img-top fixed-size-img" alt="{{ idea.name }}">
                        <div class="card-body">
                            <h5 class="card-title text-center" style="font-size: 24px;">{{ idea.title }}
                                {% if idea.status.status == 'active' %}
                                    <span class="badge rounded-pill text-bg-primary" style="font-size: 12px;">{{ idea.status.status }}</span>
                                {% elif idea.status.status == 'pending' %}
                                    <span class="badge rounded-pill text-bg-warning" style="font-size: 12px;">{{ idea.status.status }}</span>
                                {% elif idea.status.status == 'completed' %}
                                    <span class="badge rounded-pill text-bg-success" style="font-size: 12px;">{{ idea.status.status }}</span>
                                {% else %}
                                    <span class="badge rounded-pill text-bg-secondary" style="font-size: 12px;">No status</span>
                                {% endif %}
                            </h5>
                            <p class="card-text text-center" style="font-size: 20px; color: #406e59;">{{ idea.category }}</p>
                            <p class="card-text text-center">{{ idea.description }}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-body-secondary" style="display: flex; align-items: center; justify-content: center; font-size: 15px;">Author {{ idea.author }}</small>
                        </div>
                        <div class="card-footer">
                            <small class="text-body-secondary" style="display: flex; align-items: center; justify-content: center;">Last updated {{ idea.updated_at }}</small>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>


{#<!-- Filter List Idea -->#}
{#<form method="get" action="{% url 'ideas:ideas-filter' %}">#}
{#    {{ filter.form.as_p }}#}
{#    <button type="submit">Filter</button>#}
{#</form>#}

{#<ul>#}
{#    {% for idea in filter.qs %}#}
{#        <li>{{ idea.title }} - {{ idea.category }} - {{ idea.status }} - {{ idea.created_at }}</li>#}
{#    {% empty %}#}
{#        <li>No ideas found.</li>#}
{#    {% endfor %}#}
{#</ul>#}



{% endblock %}