Brainwave/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from idea import views

from contacts.views import contact_view, status_view, about_view


urlpatterns = [
    path('ideas/', include('idea.urls', namespace='ideas')),
    path('', views.index, name='index'),
    path('categories/', include('category.urls', namespace='categories')),
    path('comments/', include('comment.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path('users/', include('user.urls', namespace='users')),
    path("contacts/", contact_view, name='contact_us'),
    path("about/", about_view, name='about'),
    path("status/<str:task_id>/", status_view),
    path('partnership/', include('partnership.urls', namespace='partnership')),
    path('investments/', include('investment.urls', namespace='investments')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('direct/', include('direct.urls', namespace='directmessages'))
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

category/urls.py
from django.urls import path, include
from category import views



app_name = 'category'

urlpatterns = [
    path('', views.category_list_view, name='categories_index'),
    path('list/', views.CategoryListView.as_view(), name='list'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='detail'),
    path('create/', views.CategoryCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.CategoryUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.CategoryDeleteView.as_view(), name='delete'),
]

idea/urls.py
from django.urls import path
from idea import views
from comment import views as comment_views

app_name = 'ideas'

urlpatterns = [
    path('list/', views.IdeasListView.as_view(), name='list'),
    path('idea/<int:pk>', views.IdeasDetailView.as_view(), name='detail'),
    path('create/', views.IdeasCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.IdeasUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.IdeasDeleteView.as_view(), name='delete'),
    path('idea/<int:pk>/comment/add/', comment_views.CommentCreateView.as_view(), name='add_comment'),
    path('idea/<int:pk>/comment/edit/<int:comment_pk>/', comment_views.CommentUpdateView.as_view(), name='edit_comment'),
    path('idea/<int:pk>/comment/delete/<int:comment_pk>/', comment_views.CommentDeleteView.as_view(), name='delete_comment'),
    path('idea/<int:pk>/add_likes/', views.AddLike.as_view(), name='add_likes'),
    path('idea/<int:pk>/add_dislikes/', views.DisLike.as_view(), name='add_dislikes'),
    path('list/filter/', views.IdeasFilter.as_view(), name='ideas-filter'),
    path('idea/<int:pk>/favourites/', views.FavouriteIdeaView.as_view(), name='favourite'),
    path('idea/<int:pk>/favourites/delete/', views.FavouriteDeleteView.as_view(), name='favourite_delete'),
]

category/models.py
import os

from django.db import models

from Brainwave import settings


class Category(models.Model):
    title = models.CharField(unique=True, max_length=32)
    description = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='category_images/', default='category_images/non_category.jpg')

    def __str__(self):
        return (f"{self.title}")

category/forms.py
from django import forms
from .models import Category

class CategoryForm(forms.ModelForm):

    title = forms.CharField(
        label='Category Title',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Input Category',
                'class': 'form-control',
            }
        )
    )
    description = forms.CharField(
        label='Description',
        required=False,
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Input Category Description here',
            }
        )
    )

    image = forms.ImageField(
        label='Image',
        required=False,
    )

    class Meta:
        model = Category
        fields = '__all__'

category/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from idea.models import Idea
from .models import Category
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import CategoryForm
from user.group_permission import GroupRequiredMixin


def category_list_view(request):
    categories = Category.objects.all()
    return render(request, "category/list.html", {"categories": categories})


class CategoryListView(ListView):
    model = Category
    template_name = 'category/list.html'

class CategoryDetailView(DetailView):
    model = Category
    template_name = 'category/category_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ideas'] = Idea.objects.filter(category=self.object)
        return context

class CategoryCreateView(GroupRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'category/category_form.html'
    group_name = ["Verified", "Mods", "Admin"]

    def get_success_url(self):
        return reverse_lazy('category:detail', kwargs={'pk': self.object.pk})


class CategoryUpdateView(GroupRequiredMixin, UpdateView):
    model = Category
    fields = '__all__'
    template_name = 'category/category_update_form.html'
    group_name = ["Verified", "Mods", "Admin"]

    def get_success_url(self):
        return reverse_lazy('category:detail', kwargs={'pk': self.object.pk})


class CategoryDeleteView(GroupRequiredMixin, DeleteView):
    model = Category
    success_url = reverse_lazy('category:list')
    template_name = 'category/category_confirm_delete.html'
    group_name = ["Verified", "Mods", "Admin"]

category/templates/category/category_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete {{ object.name }} ???
{%  endblock %}

{% block body %}

    <h1>{{ object.title }}</h1>
    <h2>Description: {{ object.description }}</h2>
    <h2>Created at: {{ object.created_at }}</h2>
    <h3>Updated at: {{ object.updated_at }}</h3>


Do you confirm the deletion?
<form method="post">
    {% csrf_token %}
    <button type="submit">Yes</button>
    <button type="button" onclick="handleNoClick()">No</button>
</form>

    <script>
        function handleNoClick() {
            window.location.href = '{% url 'category:list' %}';
        }
    </script>


<a href="{% url 'category:list' %}">Back to the Category list</a>

{% endblock %}

category/templates/category/category_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.name }}
{%  endblock %}

{% block body %}

    {% if user.is_authenticated and user.is_staff %}
        <div class="mb-3">
            <a href="{% url 'category:update' pk=category.id %}" class="btn btn-primary">
                Update
            </a>
            <a href="{% url 'category:delete' pk=category.id %}" class="btn btn-danger">
                Delete
            </a>
        </div>
    {% endif %}


    <div class="row">

        <div class="col-sm-10 col-md-10 col-lg-6 col-xl-6">
            <div class="card bg-white text-grey" style="width: 475px; height: 550px;">
              <img class="card-img" src='{{ category.image.url }}' alt="Category image" style="position: absolute; bottom: 90px; width: 480px; height: 400px">
              <div class="card-img-overlay">
                  <h2 class="card-title" style="text-align: center">{{ object.title }}</h2>
                  <div id="element" style="position: absolute; bottom: 40px; text-align: center;">{{ object.description }}</div>
                      <div class="card-footer">
                          <small class="text-body-secondary" style="position: absolute; bottom: 2px; right: 120px;">Last updated {{ object.updated_at }}</small>
                      </div>

              </div>
            </div>
        </div>


    {% if ideas %}

        <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6">
            <div class="border p-3">
                  <div class="border" style="text-align: center">
                      <h3>IDEAS IN THIS CATEGORY:</h3>
                  </div>
                {% for idea in ideas %}
                    <div class="card text-center my-3">
                      <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'ideas:detail' pk=idea.id %}">{{ idea.title }}</a>

                            {% if idea.status.status == 'active' %}
                                <span class="badge rounded-pill text-bg-primary my-2" style="font-size: 13px;">{{ idea.status.status }}</span>
                            {% elif idea.status.status == 'pending' %}
                                <span class="badge rounded-pill text-bg-warning my-2" style="font-size: 13px;">{{ idea.status.status }}</span>
                            {% elif idea.status.status == 'completed' %}
                                <span class="badge rounded-pill text-bg-success my-2" style="font-size: 13px;">{{ idea.status.status }}</span>
                            {% else %}
                                <span class="badge rounded-pill text-bg-secondary my-2" style="font-size: 13px;">No status</span>
                            {% endif %}

                        </h5>
                        <p class="card-text">{{ idea.description }}</p>
                      </div>
                      <div class="card-footer text-body-secondary">
                         Posted - {{ idea.created_at }}
                      </div>
                    </div>
                {% endfor %}

                <a href="{% url 'ideas:list' %}">Go to the Idea list</a>
            </div>
        </div>

    {% else %}

        <div class="col-sm-12 col-md-10 col-lg-10 col-xl-6">
            <div class="border p-3">
                  <div class="border" style="text-align: center">
                      <h3>NO IDEAS IN THIS CATEGORY:</h3>
                    <div class="card text-center my-3">
                        <div class="card-body">
                        </div>
                      <div class="card-footer text-body-secondary">
                      </div>
                    </div>

                <a href="{% url 'ideas:create' %}">Create Idea</a>
            </div>
        </div>

    {% endif %}

    </div>



<div class="container" style="margin-top: 30px;">
    <a href="{% url 'category:list' %}">Back to the Category list</a>
</div>


{% endblock %}

category/templates/category/category_form.html
{% extends 'base.html' %}

{% block title %}
    Create Category
{%  endblock %}

{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="submit" class="button56">Create</button>
    </div>
</form>

<br>
<a href="{% url 'category:list' %}">Back to the Category list</a>

{% endblock %}

category/templates/category/category_update_form.html
{% extends 'base.html' %}

{% block title %}
    Category Update
{%  endblock %}

{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn56" type="submit">Update</button>
</form>

<br>
<a href="{% url 'category:list' %}">Back to the Category list</a>

{% endblock %}

category/templates/category/list.html
{% extends 'base.html' %}

{% block title %}
    Categories
{%  endblock %}

{% block body %}


<style>
.fixed-size-card {
    width: 100%;
    height: 600px;
}

.fixed-size-img {
    width: 100%;
    height: 300px;
    object-fit: cover;
}

.bg-blue {
    background-color: #e8fbf3;
}

.card {
    border: none;
}

.card-title, .card-text {
    color: #000000;
}

</style>

    <div class="text-center"><h1>Categories:</h1></div>
    <div class="row row-cols-1 row-cols-md-3 g-5 my-1">
        {% for category in object_list %}
            <div class="col">
                <a href="{% url 'category:detail' pk=category.id %}" class="text-decoration-none">
                    <div class="card h-100 bg-blue fixed-size-card">
                        <img src="{{ category.image.url }}" class="card-img-top fixed-size-img" alt="{{ category.title }}">
                        <div class="card-body">
                            <h5 class="card-title text-center" style="font-size: 24px;">{{ category.title }}</h5>
                            <p class="card-text text-center">{{ category.description }}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-body-secondary" style="display: flex; align-items: center; justify-content: center;">Created {{ category.created_at }}</small>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
</div>




<div class="container">
    {% include "components/back_home.html" %}
</div>

{% endblock %}