Brainwave/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from idea import views

from contacts.views import contact_view, status_view, about_view


urlpatterns = [
    path('ideas/', include('idea.urls', namespace='ideas')),
    path('', views.index, name='index'),
    path('categories/', include('category.urls', namespace='categories')),
    path('comments/', include('comment.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path('users/', include('user.urls', namespace='users')),
    path("contacts/", contact_view, name='contact_us'),
    path("about/", about_view, name='about'),
    path("status/<str:task_id>/", status_view),
    path('partnership/', include('partnership.urls', namespace='partnership')),
    path('investments/', include('investment.urls', namespace='investments')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('direct/', include('direct.urls', namespace='directmessages'))
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

idea/urls.py
from django.urls import path
from idea import views
from comment import views as comment_views

app_name = 'ideas'

urlpatterns = [
    path('list/', views.IdeasListView.as_view(), name='list'),
    path('idea/<int:pk>', views.IdeasDetailView.as_view(), name='detail'),
    path('create/', views.IdeasCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.IdeasUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.IdeasDeleteView.as_view(), name='delete'),
    path('idea/<int:pk>/comment/add/', comment_views.CommentCreateView.as_view(), name='add_comment'),
    path('idea/<int:pk>/comment/edit/<int:comment_pk>/', comment_views.CommentUpdateView.as_view(), name='edit_comment'),
    path('idea/<int:pk>/comment/delete/<int:comment_pk>/', comment_views.CommentDeleteView.as_view(), name='delete_comment'),
    path('idea/<int:pk>/add_likes/', views.AddLike.as_view(), name='add_likes'),
    path('idea/<int:pk>/add_dislikes/', views.DisLike.as_view(), name='add_dislikes'),
    path('list/filter/', views.IdeasFilter.as_view(), name='ideas-filter'),
    path('idea/<int:pk>/favourites/', views.FavouriteIdeaView.as_view(), name='favourite'),
    path('idea/<int:pk>/favourites/delete/', views.FavouriteDeleteView.as_view(), name='favourite_delete'),
]

investment/urls.py
from django.urls import path
from investment import views

app_name = 'investment'

urlpatterns = [
    path('', views.InvestorsView.as_view(), name='list'),
    path('payment/', views.CreatePaymentView.as_view(), name='payment'),
    path('payment-check/', views.PaymentCheckView.as_view(), name='payment_check'),
]

partnership/urls.py
from django.urls import path
from partnership import views


app_name = 'partnership'

urlpatterns = [
    path('', views.CoAuthorsView.as_view(), name='list'),
    path('create/<int:pk>', views.PreCoAuthorView.as_view(), name='pre_coauthor_create'),
    path('approve/<int:notification_id>', views.ApproveCoAuthor.as_view(), name='approve_coauthor'),
    path('reject/<int:notification_id>', views.RejectCoAuthor.as_view(), name='reject_coauthor'),
    path('delete/<int:pk>', views.PreCoAuthorDeleteView.as_view(), name='pre_coauthor_delete'),
    path('stop_being_coauthor/<int:pk>', views.StopBeingCoAuthor.as_view(), name='stop_being_coauthor'),
]

user/urls.py
from django.urls import path
from user import views


app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.AuthView.as_view(), name='login'),
    path('logout/', views.ExitView.as_view(), name='logout'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('profile/<int:pk>/', views.UserProfile.as_view(), name='profile'),
    path('profile/<int:pk>/ideas/', views.UserIdeas.as_view(), name='user_ideas'),
    path('profile/<int:pk>/following/', views.FollowUser.as_view(), name='following'),
    path('profile/<int:pk>/followers/', views.Followers.as_view(), name='followers'),
    path('profile/<int:pk>/partnerships/', views.UserCoAuthorIdeas.as_view(), name='partnerships'),
    path('profile/<int:pk>/favourites/', views.UserFavouritesIdeas.as_view(), name='favourites'),
    path('profile/<int:pk>/investments/', views.UserInvestmentIdeas.as_view(), name='investments'),
]

idea/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete

from notifications.models import Notification
from user.models import Follow



class Idea(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    category = models.ForeignKey('category.Category', on_delete=models.CASCADE)
    author = models.ForeignKey('user.User', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='idea_images/', default='idea_images/no_idea.jpg')
    status = models.ForeignKey("IdeaStatus", on_delete=models.CASCADE, default=1)
    co_author = models.ManyToManyField('user.User', through='partnership.CoAuthor', related_name='coauthored_ideas', blank=True)
    investors = models.ManyToManyField('user.User', through='investment.Investor', related_name='investors_ideas', blank=True)


# class IdeaImages(models.Model):
#     idea = models.ForeignKey(Idea, related_name='images', on_delete=models.CASCADE)
#     image2 = models.ImageField(upload_to='idea_images/', default='idea_images/no_idea.jpg')

    def __str__(self):
        return (f"{self.title}/{self.category}/{self.author}")

    def comments_count(self):
        return self.comments.count()

    def idea_follow(sender, instance, created, **kwargs):
        if created:
            idea = instance
            followers = idea.author.follower.all()
            for follow in followers:
                # print(f"Follower: {follow.following.username}")
                notify = Notification(idea=idea, sender=idea.author, user=follow.following, notification_type=9)
                notify.save()
    def idea_follow_delete(sender, instance, **kwargs):
            idea = instance
            followers = idea.author.follower.all()
            for follow in followers:
                notifications = Notification.objects.filter(idea=idea, sender=idea.author, user=follow.following, notification_type=9)
                notifications.delete()



class Likes(models.Model):

    idea = models.ForeignKey(Idea, verbose_name='Idea', on_delete=models.CASCADE)
    author = models.ForeignKey('user.User', verbose_name='User', on_delete=models.CASCADE)

    def user_liked_idea(sender, instance, *args, **kwargs):
        like = instance
        idea = like.idea
        sender = like.author
        notify = Notification(idea=idea, sender=sender, user=idea.author, notification_type=1)
        notify.save()

    def user_unlike_idea(sender, instance, *args, **kwargs):
        like = instance
        idea = like.idea
        sender = like.author

        notify = Notification.objects.filter(idea=idea, sender=sender, notification_type=1)
        notify.delete()



class DisLikes(models.Model):

    idea = models.ForeignKey(Idea, verbose_name='Idea', on_delete=models.CASCADE)
    author = models.ForeignKey('user.User', verbose_name='User', on_delete=models.CASCADE)

    def user_disliked_idea(sender, instance, *args, **kwargs):
        dislike = instance
        idea = dislike.idea
        sender = dislike.author
        notify = Notification(idea=idea, sender=sender, user=idea.author, notification_type=2)
        notify.save()

    def user_undislike_idea(sender, instance, *args, **kwargs):
        dislike = instance
        idea = dislike.idea
        sender = dislike.author

        notify = Notification.objects.filter(idea=idea, sender=sender, notification_type=2)
        notify.delete()


class IdeaStatus(models.Model):
    STATUS_CHOICES = [
        ('active', 'Active'),
        ('pending', 'Pending'),
        ('completed', 'Completed'),
    ]

    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    updated_by = models.ForeignKey('user.User', on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.status

class Favourite(models.Model):
    idea = models.ForeignKey(Idea, verbose_name='Idea', on_delete=models.CASCADE, related_name='favourite')
    user = models.ForeignKey('user.User', verbose_name='User', on_delete=models.CASCADE, related_name='user')


# Likes
post_save.connect(Likes.user_liked_idea, sender=Likes)
post_delete.connect(Likes.user_unlike_idea, sender=Likes)
# DisLikes
post_save.connect(DisLikes.user_disliked_idea, sender=DisLikes)
post_delete.connect(DisLikes.user_undislike_idea, sender=DisLikes)
# Idea Follow
post_save.connect(Idea.idea_follow, sender=Idea)
post_delete.connect(Idea.idea_follow_delete, sender=Idea)

partnership/forms.py
from django import forms
from .models import PreCoAuthor

class PreCoAuthorForm(forms.ModelForm):

    class Meta:
        model = PreCoAuthor
        exclude = ['user', 'idea']

investment/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView
from django.views import View

from investment.models import Investor, InvestorPayment
from investment.payments import create_payment, fetch_all_payments

from yookassa import Payment


class InvestorsView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Investor
    template_name = 'investments/investors.html'

    def test_func(self):
        return self.is_user_in_group()

    def is_user_in_group(self):
        return self.request.user.is_staff or self.request.user.groups.filter(name="Investor").exists()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        investor_payments = InvestorPayment.objects.all()
        context['all_payments'] = fetch_all_payments()
        context['all_investor_payments'] = investor_payments

        # pending_payments = InvestorPayment.objects.filter(status='pending')
        # if pending_payments:
        #     for payment in pending_payments:
        #         yookassa_payment = Payment.find_one(payment.payment_id)
        #         print(f"yookassa_payment = {yookassa_payment.status}")
        #         print(f"payment.status BEFORE = {payment.status}")
        #         payment.status = yookassa_payment.status
        #         payment.save()
        #         print(f"payment.status after = {payment.status}")
        # else:
        #     print(f"No pendings")
        return context

class CreatePaymentView(View):
    def get(self, request):
        return render(request, 'investments/payment.html')

    def post(self, request):
        user = self.request.user
        amount = float(request.POST.get('amount'))
        full_url = request.build_absolute_uri('/investments/payment-check/')
        confirmation_url, payment_id = create_payment(amount, full_url, user)

        payment_detail = Payment.find_one(payment_id)
        payment_detail_dict = {
            'id': payment_detail.id,
            'status': payment_detail.status,
        }
        request.session['payment_detail'] = payment_detail_dict

        return redirect(confirmation_url)


class PaymentCheckView(View):
    def get(self, request):
        payment_detail_dict = request.session.get('payment_detail')

        # if 'payment_detail' in request.session:
        #     del request.session['payment_detail']

        context = {'payment_detail': payment_detail_dict}

        return render(request, 'investments/payment_check.html', context)

partnership/views.py
from django.views.generic import ListView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Min
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.db.models.signals import post_save, post_delete
from django.views import View

from idea.models import Idea
from .forms import PreCoAuthorForm
from partnership.models import CoAuthor, PreCoAuthor
from notifications.models import Notification


class CoAuthorsView(LoginRequiredMixin, ListView):
    model = CoAuthor
    template_name = 'partnership/coauthors.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        idea_coauthors_dict = {}

        ideas = Idea.objects.annotate(
            earliest_joined_at=Min('coauthor__joined_at')
        ).order_by('-earliest_joined_at')
        ideas_dict = {idea: list(idea.co_author.all()) for idea in ideas}
        new_list = []
        for idea_id, coauthor in ideas_dict.items():
            if coauthor:
                new_list.append([idea_id, coauthor])
                # print(f'new list = {new_list}')
                # print(f'coauthor = {coauthor}')

        idea_enumerate = enumerate(new_list, start=1)

        users = []
        us_list = []
        ideas_list = [] # [<Idea: CodeForKids/Society/user>, <Idea: Creative4343/Creative/artyombn>]
        final_users = set()
        model_ideas = {}
        for query in new_list: # [[<Idea: CodeForKids/Society/user>, [<User: test>, <User: artyombn>]], [<Idea: Creative4343/Creative/artyombn>, [<User: user>, <User: test>]]]
            ideas_list.append(query[0])
            for elements in query[1]:
                user = CoAuthor.objects.filter(user=elements, idea=query[0])
                users.append(user)
            us_list.append(list(users))
            users.clear()


        coauthor_list = [] # [<CoAuthor: test - CodeForKids - >, <CoAuthor: artyombn - CodeForKids - >, <CoAuthor: user - Creative4343 - Developer>, <CoAuthor: test - Creative4343 - >]
        for us22 in us_list:
            for q in us22:
                for t in q:
                    # print(f'us = {t} type - {type(t)}')
                    # print(f'idea title = {t.idea}')
                    coauthor_list.append(t)

            for coauthor in coauthor_list:
                idea = coauthor.idea
                if idea in ideas:
                    if idea not in idea_coauthors_dict:
                        idea_coauthors_dict[idea] = []
                        idea_coauthors_dict[idea].append(coauthor)
                    else:
                        idea_coauthors_dict[idea].append(coauthor)


        context['idea_enumerate'] = idea_enumerate
        context['model_coauthor'] = model_ideas
        context['idea_coauthors_dict'] = idea_coauthors_dict
        context['coauthor_list'] = coauthor_list

        return context



class PreCoAuthorView(CreateView):
    model = PreCoAuthor
    form_class = PreCoAuthorForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.idea = get_object_or_404(Idea, pk=self.kwargs.get("pk"))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('ideas:detail', kwargs={'pk': self.object.idea.pk})


class PreCoAuthorDeleteView(DeleteView):
    model = PreCoAuthor

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        return reverse_lazy('ideas:detail', kwargs={'pk': self.object.idea.pk})

class ApproveCoAuthor(View):
    def post(self, request, notification_id):
        notification = get_object_or_404(Notification, id=notification_id)
        idea = notification.idea
        user = notification.sender

        CoAuthor.objects.create(idea=idea, user=user)
        precoauthor = PreCoAuthor.objects.filter(idea=idea, user=user)
        precoauthor.delete()

        return redirect('notifications:show-notifications')


class RejectCoAuthor(View):
    def post(self, request, notification_id):
        notification = get_object_or_404(Notification, id=notification_id)
        idea = notification.idea
        user = notification.sender

        precoauthor = PreCoAuthor.objects.filter(idea=idea, user=user).first()
        if precoauthor:
            precoauthor.is_rejected = True
            precoauthor.save()
            precoauthor.delete()

        return redirect('notifications:show-notifications')



class StopBeingCoAuthor(View):
    def post(self, request, pk):
        idea = get_object_or_404(Idea, pk=pk)
        user = request.user

        coauthor = CoAuthor.objects.filter(idea=idea, user=user)
        coauthor.delete()

        next_page = request.GET.get('next', 'ideas:detail')
        if next_page == 'ideas:detail':
            return redirect('ideas:detail', pk=idea.pk)
        elif next_page == 'users:partnerships':
            return redirect('users:partnerships', pk=user.id)
        else:
            return redirect('ideas:detail', pk=idea.pk)

class CoAuthorDeleteView(View):
    def post(self, request, pk):
        idea = get_object_or_404(Idea, pk=pk)
        user = request.user

        coauthor = CoAuthor.objects.filter(idea=idea, user=user)
        coauthor.delete()

        return redirect('ideas:detail', pk=idea.pk)

user/templates/user/favourites.html
{% extends 'base.html' %}

{% block title %}
    My Favourites Idea
{%  endblock %}

{% block body %}

<h3 style="text-transform: uppercase">My Favourite Ideas</h3>


{% for favourite in favourites_ideas %}
    <ul>
        <li>Idea: <a href="{% url 'ideas:detail' pk=favourite.idea.id %}" style="text-decoration: none">{{ favourite.idea.title }}</a>
        <a href="{% url 'ideas:favourite_delete' favourite.idea.id %}" class="fav-button">
            <span class="fav-icon" data-bs-toggle="tooltip" data-bs-placement="top" title="">
                <img src="/media/social_media/remove.png" width="30px" height="30px">
            </span>
        </a>
        </li>
        <li>Description: {{ favourite.idea.description }}</li>
    </ul>
{% endfor %}

<br>
<br>
<a href="{% url 'index' %}">Back Home page</a>

{% endblock %}

user/templates/user/followers.html
{% extends 'base.html' %}

{% block title %}
    My Followers
{%  endblock %}

{% block body %}

<h3 style="text-transform: uppercase">My Followers</h3>
    <br>
    {% for follower in request.user.follower.all %}
        <li>{{ follower.following.first_name }} {{ follower.following.last_name }}
        <strong><small><a href="{% url 'users:profile' pk=follower.following.id %}" style="text-decoration: none">@{{ follower.following.username }}</a></small></strong>
        </li>
    {% endfor %}
<br>

<p>I'm Following:
    {% for followed in request.user.following.all %}
        <li>{{ followed.follower.first_name }} {{ followed.follower.last_name }}
            <strong><small><a href="{% url 'users:profile' pk=followed.follower.id %}" style="text-decoration: none">@{{ followed.follower.username }}</a></small></strong>
            <a href="{% url 'users:following' followed.follower.id %}?next=users:following" style="text-decoration: none; margin-left: 10px;">
                <img src="/media/social_media/unfollowuser.png" width="26px" height="26px">
            </a>
        </li>
    {% endfor %}
</p>

<br>
<br>
<a href="{% url 'index' %}">Back Home page</a>

{% endblock %}

user/templates/user/ideas.html
{% extends 'base.html' %}

{% block title %}
    My Ideas
{%  endblock %}

{% block body %}

<h3 style="text-transform: uppercase">My Ideas</h3>

{% for idea in object_list %}
    <li><a href="{% url 'ideas:detail' pk=idea.id %}">{{ idea.title }} -- {{ idea.description }}</a></li>
{% endfor %}
<br>
<br>
<a href="{% url 'index' %}">Back Home page</a>

{% endblock %}

user/templates/user/investments.html
{% extends 'base.html' %}

{% block title %}
    My Investments
{%  endblock %}

{% block body %}

<h3 style="text-transform: uppercase">My Investments</h3>

{% for investor in user_investments %}
            <ul>
                <li>
                    <small>
                        Payment id: {{ investor.payment_id }}<br>
                        Amount: <strong>{{ investor.amount }} RUB</strong><br>
                        Description: {{ investor.description }}<br>
                        Paid:
                        {% if investor.paid %}
                            <span style="color: #6ecc4b">{{ investor.paid }}</span><br>
                        {% else %}
                            <span style="color: #f45a5a">{{ investor.paid }}</span><br>
                        {% endif %}

                        Payment method: {{ investor.payment_method }}<br>
                        Status:
                        {% if investor.status == "pending" %}
                            <span style="color: #efef7c">{{ investor.status }}</span><br>
                        {% elif investor.status == "succeeded" %}
                            <span style="color: #6ecc4b">{{ investor.status }}</span><br>
                        {% elif investor.status == "waiting_for_capture" %}
                            <span style="color: #5c72f8">waiting_for_capture -{{ investor.status }}</span><br>
                        {% else %}
                            {{ investor.status }}<br>
                        {% endif %}
                    </small>
                </li>
            </ul>

        {% endfor %}

<br>
<br>
<a href="{% url 'index' %}">Back Home page</a>

{% endblock %}

user/templates/user/list.html
{% extends 'base.html' %}

{% block title %}
    Users
{%  endblock %}

{% block body %}

{% load user_tags %}

    <h1 class="my-4 text-center">USERS:</h1>

    <div class="container">
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            {% for user in users %}
                <div class="col">
                    <div class="card">
                        <a href="{% url 'users:profile' pk=user.pk %}">
                            <img src="{{ user.avatar.url }}" class="card-img-top rounded-circle" alt="Avatar" style="width: 150px; height: 150px; object-fit: cover;">
                        </a>
                        <div class="card-body">
                            <a href="{% url 'users:profile' pk=user.pk %}" style="text-decoration: none; color: #0c8e5e">
                                <h5 class="card-title" style="font-size: 30px;">{{ user }}
                                {% if user|check_in_group:"Admin" %}
                                    <img src="/media/user_groups/admin.png" alt="admin" width="40" height="40">
                                {% endif %}

                                </h5>
                            </a>
                            <p class="card-text"><small>Email: {{ user.email }}</small></p>
                            <p class="card-text"><small>First name: {{ user.first_name }}</small></p>
                            <p class="card-text"><small>Last name: {{ user.last_name }}</small></p>
                            <p class="card-text"><small>Age: {{ user.age }}</small></p>
                            <p class="card-text"><small>Groups:
                                {% if user.groups.all %}
                                    {% for group in user.groups.all %}
                                        {{ group }} /
                                    {% endfor %}
                                {% else %}
                                    User doesn't have groups
                                {% endif %}
                                </small>
                            </p>

                                <div class="card" style="width: 20rem; margin-top: 2rem;">
                                    <div class="card-body">
                                        <p class="card-text" style="font-style: initial; text-align: center">
                                            <small>
                                                <span style="font-weight: bold; text-transform: uppercase;">{{ user }}</span>'s Ideas:
                                                <ul style="list-style: none; padding: 0;">
                                                    {% for idea in user.idea_set.all %}
                                                        <li>
                                                            <a href="{% url 'ideas:detail' pk=idea.pk %}" style="display: block; text-align: center;">
                                                                {{ idea.title }}
                                                            </a>
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            </small>
                                        </p>
                                    </div>
                                </div>


                            <p style="margin-top: 2rem;"><small>Join date: {{ user.date_joined }} </small></p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="container my-4">
        {% include "components/back_home.html" %}
    </div>

{% endblock %}

user/templates/user/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{%  endblock %}

{% block body %}

<form method="post" style="margin-top: -20px;">
    {% csrf_token %}
        {{ form.as_p }}

    <div class="d-grid my-2">
        <button type="submit" class="button56">Login</button>
    </div>
</form>

<br>
<div class="container">
    {% include "components/back_home.html" %}
</div>

{% endblock %}

user/templates/user/partnerships.html
{% extends 'base.html' %}

{% block title %}
    My Partnerships
{%  endblock %}

{% block body %}

<h3 style="text-transform: uppercase">My Partnerships</h3>


{% for co_author_idea in co_author_ideas %}
    <ul>
        <li>Idea: <a href="{% url 'ideas:detail' pk=co_author_idea.idea.id %}" style="text-decoration: none">{{ co_author_idea.idea.title }}</a></li>
        <li>Description: {{ co_author_idea.idea.description }}</li>
        <li>Role: {{ co_author_idea.role }}</li>

        <form method="post" action="{% url 'partnership:stop_being_coauthor' pk=co_author_idea.idea.id %}?next=users:partnerships">
            {% csrf_token %}
            <button type="submit" class="btn btn-warning mb-5">Stop being Co-Author</button>
        </form>
    </ul>
{% endfor %}

<br>
<br>
<a href="{% url 'index' %}">Back Home page</a>

{% endblock %}

user/templates/user/profile.html
{% extends 'base.html' %}

{% block title %}
    {% if request.user.id == user.id %}
        Your Profile
    {% else %}
        {{ object.username }}'s Profile
    {% endif %}

{%  endblock %}

{% block body %}

{% load user_tags %}

<h1 style="text-transform: uppercase">{{ object.username }} Profile

    {% if object|check_in_group:"Admin" %}
        <img src="/media/user_groups/admin.png" alt="admin" width="40" height="40">
    {% endif %}

    {% if request.user != user %}
        {% if check %}
            <a href="{% url 'users:following' user.id %}?next=users:profile" style="text-decoration: none; margin-left: 15px;">
                <img src="/media/social_media/unfollowuser.png" alt="follow" width="50" height="50">
            </a>
        {% else %}
            <a href="{% url 'users:following' user.id %}?next=users:profile" style="text-decoration: none; margin-left: 15px;">
                <img src="/media/social_media/followuser.png" alt="follow" width="50" height="50">
            </a>
        {% endif %}
    {% endif %}
</h1>
<img src="{{ object.avatar.url }}" alt="Avatar" width="120" height="120" class="m-3">

{% if request.user.id == user.id %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ profile_form.as_p }}

        <div class="d-grid mx-auto">
            <button type="submit" class="button56">Update</button>
        </div>
    </form>
{% else %}
    <p>Username: {{ object.username }}</p>
    <p>First Name: {{ object.first_name }}</p>
    <p>Last Name: {{ object.last_name }}</p>
    <p>Email: {{ object.email }}</p>
    <p>Age: {{ object.age }}</p>

    <br>

    <br>
    <p>{{ user.first_name }}'s Followers:
        {% for following in object.follower.all %}
            <li><strong>{{ following.following.first_name }} {{ following.following.last_name }}</strong>
            <small>@{{ following.following.username }}</small></li>
        {% endfor %}
    </p>
    <br>

    <p>Followed:
        {% for followers in object.following.all %}
            <li><strong>{{ followers.follower.first_name }} {{ followers.follower.last_name }}</strong>
            <small>@{{ followers.follower.username }}</small></li>
        {% endfor %}
    </p>
    <br>

{% endif %}

<br>
{% if request.user.id != user.id %}
    <h3 style="text-transform: uppercase">{{ object.first_name }}'s Ideas</h3>
    <br>
    {% for idea in ideas %}
        <li><a href="{% url 'ideas:detail' pk=idea.pk %}">{{ idea.title }} -- {{ idea.description }}</a></li>
    {% endfor %}
{% endif %}

<br>

<a href="{% url 'index' %}">Back Home page</a>

{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}

{% block title %}
    Registration
{%  endblock %}

{% block body %}

<form method="post" style="margin-top: -20px;>
    {% csrf_token %}
    {{ form.as_p }}

    <div class="d-grid my-2">
        <button type="submit" class="button56">Register</button>
    </div>
</form>

<br>
<div class="container">
    {% include "components/back_home.html" %}
</div>

{% endblock %}