Brainwave/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from idea import views

from contacts.views import contact_view, status_view, about_view


urlpatterns = [
    path('ideas/', include('idea.urls', namespace='ideas')),
    path('', views.index, name='index'),
    path('categories/', include('category.urls', namespace='categories')),
    path('comments/', include('comment.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('admin/', admin.site.urls),
    path('users/', include('user.urls', namespace='users')),
    path("contacts/", contact_view, name='contact_us'),
    path("about/", about_view, name='about'),
    path("status/<str:task_id>/", status_view),
    path('partnership/', include('partnership.urls', namespace='partnership')),
    path('investments/', include('investment.urls', namespace='investments')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('direct/', include('direct.urls', namespace='directmessages'))
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

category/urls.py
from django.urls import path, include
from category import views



app_name = 'category'

urlpatterns = [
    path('', views.category_list_view, name='categories_index'),
    path('list/', views.CategoryListView.as_view(), name='list'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='detail'),
    path('create/', views.CategoryCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.CategoryUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.CategoryDeleteView.as_view(), name='delete'),
]

comment/urls.py
from django.urls import path
from comment import views


app_name = 'comment'

urlpatterns = [
    path('', views.comments_list_view, name='comments_index'),
    path('list/', views.CommentListView.as_view(), name='list'),
    path('comment/<int:pk>', views.CommentDetailView.as_view(), name='detail'),
    path('create/', views.CommentCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.CommentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.CommentDeleteView.as_view(), name='delete'),
    path('like/<int:pk>/', views.CommentLike.as_view(), name='comment_like'),
]

direct/urls.py
from django.urls import path

from . import views

app_name = 'direct'

urlpatterns = [
    path('messages/', views.MessagesList.as_view(), name='messages'),
    path('load-messages/', views.LoadMessagesView.as_view(), name='load_messages'),
]

idea/urls.py
from django.urls import path
from idea import views
from comment import views as comment_views

app_name = 'ideas'

urlpatterns = [
    path('list/', views.IdeasListView.as_view(), name='list'),
    path('idea/<int:pk>', views.IdeasDetailView.as_view(), name='detail'),
    path('create/', views.IdeasCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.IdeasUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.IdeasDeleteView.as_view(), name='delete'),
    path('idea/<int:pk>/comment/add/', comment_views.CommentCreateView.as_view(), name='add_comment'),
    path('idea/<int:pk>/comment/edit/<int:comment_pk>/', comment_views.CommentUpdateView.as_view(), name='edit_comment'),
    path('idea/<int:pk>/comment/delete/<int:comment_pk>/', comment_views.CommentDeleteView.as_view(), name='delete_comment'),
    path('idea/<int:pk>/add_likes/', views.AddLike.as_view(), name='add_likes'),
    path('idea/<int:pk>/add_dislikes/', views.DisLike.as_view(), name='add_dislikes'),
    path('list/filter/', views.IdeasFilter.as_view(), name='ideas-filter'),
    path('idea/<int:pk>/favourites/', views.FavouriteIdeaView.as_view(), name='favourite'),
    path('idea/<int:pk>/favourites/delete/', views.FavouriteDeleteView.as_view(), name='favourite_delete'),
]

notifications/urls.py
from django.urls import path
from notifications import views

app_name = 'notifications'

urlpatterns = [
    path('', views.ShowNotifications, name='show-notifications'),
    path('delete/<int:id>', views.DeleteNotification, name='delete-notification'),
    path('deleteall/', views.DeleteAllNotifications, name='delete-all-notifications'),
]

user/urls.py
from django.urls import path
from user import views


app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.AuthView.as_view(), name='login'),
    path('logout/', views.ExitView.as_view(), name='logout'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('profile/<int:pk>/', views.UserProfile.as_view(), name='profile'),
    path('profile/<int:pk>/ideas/', views.UserIdeas.as_view(), name='user_ideas'),
    path('profile/<int:pk>/following/', views.FollowUser.as_view(), name='following'),
    path('profile/<int:pk>/followers/', views.Followers.as_view(), name='followers'),
    path('profile/<int:pk>/partnerships/', views.UserCoAuthorIdeas.as_view(), name='partnerships'),
    path('profile/<int:pk>/favourites/', views.UserFavouritesIdeas.as_view(), name='favourites'),
    path('profile/<int:pk>/investments/', views.UserInvestmentIdeas.as_view(), name='investments'),
]

comment/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete

class Comment(models.Model):
    idea = models.ForeignKey('idea.Idea', related_name='comments', on_delete=models.CASCADE, default=1)
    author = models.ForeignKey('user.User', related_name='comments', on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def comment_post(sender, instance, *args, **kwargs):
        from idea.models import Idea
        from notifications.models import Notification
        comment = instance
        sender = comment.author
        idea = Idea.objects.get(id=comment.idea.id)
        user = idea.author
        comment_text = comment.text
        notify = Notification.objects.create(idea=idea, sender=sender, user=user, text_preview=comment_text, notification_type=3)
        notify.save()

    def comment_delete(sender, instance, *args, **kwargs):
        from idea.models import Idea
        from notifications.models import Notification
        comment = instance
        sender = comment.author
        idea = Idea.objects.get(id=comment.idea.id)
        user = idea.author

        notify = Notification.objects.filter(sender=sender, user=user, idea=idea, notification_type=3)
        notify.delete()


    def __str__(self):
        return (
            f"Text: {self.text}, -- "
            f"Under idea: {self.idea}, -- "
            f"Author: {self.author}, -- "
            f"Created_at: {self.created_at}"
        )

class CommentLikes(models.Model):

    author = models.ForeignKey('user.User', verbose_name='User', on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, verbose_name='Comment', on_delete=models.CASCADE)



post_save.connect(Comment.comment_post, sender=Comment)
post_delete.connect(Comment.comment_delete, sender=Comment)

comment/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    text = forms.CharField(
        label='Comment text',
        # required=False,
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Write your comment here',
                'class': 'form-control',
                'rows': 5
            }
        )
    )


    class Meta:
        model = Comment
        fields = ('text',)

comment/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
import json
from django.views.generic.base import View

from idea.models import Idea
from .forms import CommentForm
from .models import Comment, CommentLikes
from user.group_permission import GroupRequiredMixin


class BaseCommentView(GroupRequiredMixin):
    model = Comment
    group_name = "User"

    def get_success_url(self):
        idea = self.object.idea
        return reverse(
            "ideas:detail",
            kwargs={"pk": idea.pk},
        )

def comments_list_view(request):

    comments = Comment.objects.all().order_by("-created_at")
    return render(request, "comment/list.html", {"comments": comments})

class CommentListView(ListView):
    model = Comment
    template_name = 'comment/list.html'
    # paginate_by = 10


class CommentDetailView(LoginRequiredMixin, DetailView):
    model = Comment
    template_name = 'comment/comment_detail.html'

    def check_comment_like(self):
        comment = self.get_object()
        if comment.commentlikes_set.all().count() == 0:
            return f'No likes yet'
        else:
            comment_likers = []
            for comment in comment.commentlikes_set.all():
                comment_likers.append(comment)
            result = ', '.join(comment_likers)
        return f'Liked: {result}'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['check_comment_like'] = self.check_comment_like()
        return context

class CommentCreateView(GroupRequiredMixin, CreateView):
    form_class = CommentForm
    group_name = ["User"]
    # template_name = 'comment/comment_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.idea = get_object_or_404(Idea, pk=self.kwargs.get("pk"))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('comment:detail', kwargs={'pk': self.object.pk})


class CommentUpdateView(UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'comment/comment_update_form.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        data = json.loads(request.body)
        comment.text = data.get('text', comment.text)
        comment.save()
        return JsonResponse({'text': comment.text})

    # redirect
    #

    def get_object(self, queryset=None):
        comment = super().get_object(queryset)
        self.comment = comment
        return comment

    def get_success_url(self):
        return reverse_lazy('ideas:detail', kwargs={'pk': self.comment.idea.pk})

    def test_func(self):
        comment = self.get_object()
        return self.request.user.is_staff or comment.author == self.request.user

class CommentDeleteView(BaseCommentView, UserPassesTestMixin, DeleteView):
    template_name = 'comment/comment_confirm_delete.html'

    def get_object(self, queryset=None):
        comment = super().get_object(queryset)
        self.comment = comment
        return comment

    def get_success_url(self):
        return reverse_lazy('ideas:detail', kwargs={'pk': self.comment.idea.pk})


    def test_func(self):
        return self.author_or_staff_permission()

    def author_or_staff_permission(self):
        comment = get_object_or_404(Comment, pk=self.kwargs['pk'])
        return self.request.user.is_staff or comment.author == self.request.user



class CommentLike(View):

    def get(self, request, pk):
        user = request.user
        if user.is_authenticated:
            if CommentLikes.objects.filter(comment_id=pk, author=user).exists():
                comment = Comment.objects.get(pk=pk)
                idea_id = comment.idea.id
                like = CommentLikes.objects.get(comment_id=pk, author=user)
                like.delete()
                return redirect(reverse('ideas:detail', kwargs={'pk': idea_id}))
            else:
                comment = Comment.objects.get(pk=pk)
                new_like = CommentLikes()
                new_like.author = request.user
                new_like.comment = comment
                new_like.save()
                idea_id = comment.idea.id
                return redirect(reverse('ideas:detail', kwargs={'pk': idea_id}))
        else:
            return redirect(reverse('users:login'))

templates/components/403_forbidden_splash.html
{% extends 'base.html' %}

{% block title %}
    403 Ащкишввут
{%  endblock %}

{% block body %}

    <h1>Access denied</h1>

    {% include "components/403.html" %}

<div class="container">
    {% include "components/back_home.html" %}
</div>

{% endblock %}

templates/components/back_home.html
<a href="{% url 'index' %}">Back home</a>

templates/components/categories_card.html
<style>
    #carouselExampleCaptions {
      width: 1400px !important;
      height: 200px !important;
    }

    #carouselExampleCaptions .carousel-inner {
      height: 200px !important;
    }

    #carouselExampleCaptions .carousel-item img {
      height: 200px !important;
      object-fit: cover !important;
    }
  </style>


<div class="d-flex justify-content-center">
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      {% for category in categories %}
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}" aria-current="true" aria-label="Slide {{ forloop.counter }}"></button>
      {% endfor %}
    </div>
    <div class="carousel-inner" style="height: 400px;">
      {% for category in categories %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
          <img src="{{ category.image.url }}" class="d-block w-100" alt="{{ category.title }}">
          <a href="{% url 'category:detail' category.id %}" style="text-decoration: none;">
            <div class="carousel-caption d-none d-md-block">
              <h5 class="text-bg-light">{{ category.title }}</h5>
              <p class="text-bg-light">{{ category.description }}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

templates/components/filter.html
<style>
.filter-container select {
    width: 300px;
    padding: 5px;
    border: 2px solid #119ae4;
    border-radius: 5px;
}


.filter-container > * {
    margin-right: 5px;
    color: black;
}

.btn-full-width {
  width: 100%;
  display: block;
}

.btn.btn-success {
    padding: 2px 10px;
    width: 100px;
    height: 40px;
    font-size: 12px;
    margin-top: 50px;
    color: #ffffff;

.form-group {
    display: flex;
    flex-direction: column;
    gap: 30px;
}
}

</style>

<div class="container my-4">
    <!-- Filter button -->
    <button class="btn btn-primary btn-full-width" type="button" data-bs-toggle="collapse" data-bs-target="#filters" aria-expanded="false" aria-controls="filters">
      Filters
    </button>

    <!-- Filters -->
    <div class="collapse mt-3" id="filters">
      <div class="card card-body">
        <form method="GET" action="{% url 'index' %}">
          <div class="d-flex filter-container">

            <!-- Category filter -->
            <div class="mb-3 flex-grow-1">
              <label for="categoryFilter" class="form-label">Category</label>
              <select class="form-select" id="categoryFilter" name="category">
                <option value="" {% if not request.GET.category %}selected{% endif %}>All Categories</option>
                {% for category in categories %}
                    <option value="{{ category.id }}" {% if request.GET.category == category.id|stringformat:"s" %}selected{% endif %}>{{ category.title }}</option>
                {% endfor %}
              </select>
            </div>

            <!-- Status filter -->
            <div class="mb-3 flex-grow-1">
              <label for="statusFilter" class="form-label">Status</label>
              <select class="form-select" id="statusFilter" name="status">
                <option value="" {% if not request.GET.status %}selected{% endif %}>All Statuses</option>
                {% for status in statuses %}
                    <option value="{{ status.status }}" {% if request.GET.status == status.status %}selected{% endif %}>{{ status.status }}</option>
                {% endfor %}
              </select>
            </div>

             <!-- Sort By -->
            <div class="mb-3 flex-grow-1">
              <label for="sortFilter" class="form-label">Sort By</label>
              <select class="form-select" id="sortFilter" name="sort">
                <option value="" {% if not request.GET.sort %}selected{% endif %}>Sort by</option>
                <option value="1" {% if request.GET.sort == '1' %}selected{% endif %}>Most Liked</option>
                <option value="2" {% if request.GET.sort == '2' %}selected{% endif %}>Most Commented</option>
                <option value="3" {% if request.GET.sort == '3' %}selected{% endif %}>Date ↑</option>
                <option value="4" {% if request.GET.sort == '4' %}selected{% endif %}>Date ↓</option>
              </select>
            </div>

                <!-- Co-Authors filter -->
                <div class="form-group">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" id="coAuthorsFilter" name="co_authors" {% if request.GET.co_authors %}checked{% endif %}>
                        <label class="form-check-label" for="coAuthorsFilter">
                            Co-Authors
                        </label>
                    </div>

                <!-- Investors filter -->
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="1" id="investorsFilter" name="investors" {% if request.GET.investors %}checked{% endif %}>
                        <label class="form-check-label" for="investorsFilter">
                            Investors
                        </label>
                    </div>
                </div>

            <!-- Apply Filter button -->
            <button type="submit" class="btn btn-success">Apply Filters</button>
          </div>
        </form>
      </div>
    </div>
</div>

templates/components/footer.html
<!-- Site footer -->
<footer class="site-footer">
    <div class="footer-content">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6>About</h6>
                <p class="text-justify">BrainWave - <i>YOUR HUB</i> for idea exploration and exchange! Here, you can register your creative concepts, find co-authors and investors to bring them to life, rate ideas from the community, and receive feedback from experienced users. Join our community and turn your thoughts into reality!</p>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Categories</h6>
                <ul class="footer-links">
                    <li><a href="#">Link#1</a></li>
                    <li><a href="#">Link#2</a></li>
                    <li><a href="#">Link#3</a></li>
                </ul>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Quick Links</h6>
                <ul class="footer-links">
                    <li><a href="{% url 'about' %}">About Us</a></li>
                    <li><a href="{% url 'contact_us' %}">Contact Us</a></li>
                    <li><a href="#">Link#3</a></li>
                    <li><a href="#">Link#4</a></li>
                </ul>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">Copyright &copy; 2024</p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <ul class="social-icons">
                    <li><a class="facebook" href="https://www.facebook.com/artyomnb"><img src="/media/social_media/facebook.png" alt="facebook;"></a></li>
                    <li><a class="telegram" href="https://t.me/artyombn"><img src="/media/social_media/telegram.png" alt="telegram;"></a></li>
                    <li><a class="gmail" href="mailto:balabashinan@gmail.com"><img src="/media/social_media/gmail.png" alt="gmail;"></a></li>
                    <li><a class="linkedin" href="https://www.linkedin.com/in/artembn"><img src="/media/social_media/linkedin.png" alt="linkedin;"></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/components/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href='{% url 'index' %}'>BrainWave</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                <li class="nav-item">
                    <a class="nav-link" href='{% url 'ideas:list' %}'>Ideas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='{% url 'category:list' %}'>Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='{% url 'investments:list' %}'>Investments</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='{% url 'partnership:list' %}'>Partnerships</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href='{% url 'category:list' %}'>Leaderboard</a>
                </li>
                {% if request.user.is_authenticated and request.user.is_staff %}
                    {% include 'components/navbar_dropdown.html' %}
                {% endif %}
            </ul>
            <form class="d-flex ms-auto me-3" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" style="width: 200px">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        <ul class="navbar-nav ms-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item text-light me-lg-3 my-1">
                    {% include 'components/profile_dropdown.html' %}
                </li>
                <li class="nav-item me-lg-2">
                    <form method="post" action='{% url 'users:logout' %}'>
                        {% csrf_token %}
                        <button type="submit" class="Btnlogout">
                            <div class="signlogout">
                                <svg viewBox="0 0 512 512">
                                    <path d="M377.9 105.9L500.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L377.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1-128 0c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM160 96L96 96c-17.7 0-32 14.3-32 32l0 256c0 17.7 14.3 32 32 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32l-64 0c-53 0-96-43-96-96L0 128C0 75 43 32 96 32l64 0c17.7 0 32 14.3 32 32s-14.3 32-32 32z"></path>
                                </svg>
                            </div>
                            <div class="textlogout">Logout</div>
                        </button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'users:register' %}" class="nav-link">Sign up</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'users:login' %}" class="nav-link">Sign in</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<style>
/*
=========================
Button Logout
=========================
*/

.Btnlogout {
  display: flex;
  align-items: center;
  justify-content: flex-start;
  width: 30px;
  height: 30px;
  border: none;
  border-radius: 40%;
  cursor: pointer;
  position: relative;
  overflow: hidden;
  transition-duration: .3s;
  box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.199);
  background-color: rgb(255, 186, 0);
  margin-top: 8px;
}

/* plus sign */
.signlogout {
  width: 100%;
  transition-duration: .3s;
  display: flex;
  align-items: center;
  justify-content: center;
}

.signlogout svg {
  width: 17px;
}

.signlogout svg path {
  fill: #000000;
}
/* text */
.textlogout {
  position: absolute;
  right: 0%;
  width: 0%;
  opacity: 0;
  color: #000000;
  font-size: 1em;
  font-weight: 400;
  transition-duration: .3s;
}
/* hover effect on button width */
.Btnlogout:hover {
  width: 110px;
  border-radius: 40px;
  transition-duration: .3s;
}

.Btnlogout:hover .signlogout {
  width: 40%;
  transition-duration: .3s;
  padding-left: 5px;
}
/* hover effect button's text */
.Btnlogout:hover .textlogout {
  opacity: 1;
  width: 70%;
  transition-duration: .3s;
  padding-right: 10px;
}
/* button click effect*/
.Btnlogout:active {
  transform: translate(2px ,2px);
}
</style>

templates/components/navbar_dropdown.html
<li class="nav-item dropdown">

            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                ADMIN
            </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/admin/">Admin Panel</a></li>
                    <li><a class="dropdown-item" href="{% url 'ideas:create' %}">Add New Idea</a></li>
                    <li><a class="dropdown-item" href="{% url 'category:create' %}">Add New Category</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'users:users' %}">All Users</a></li>
                    <li><a class="dropdown-item" href="{% url 'comment:list' %}">All Comments</a></li>
                    <li><a class="dropdown-item " href="{% url 'investment:list' %}">All Investments</a></li>
                    <li><a class="dropdown-item" href="{% url 'partnership:list' %}">All Partnerships</a></li>
                </ul>
            </li>
{#                <li class="nav-item">#}
{#                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>#}
{#                </li>#}
            </ul>

templates/components/profile_dropdown.html
<li class="nav-item dropdown">
    <a class="nav-link" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false" style="display: flex; align-items: center;">
        <img src="{{ request.user.avatar.url }}" alt="Аватар" width="40" height="40" style="border-radius: 50%;">
        <span style="margin-left: 10px; color: white;">{{ request.user.username }}</span>

        {% load user_tags %}

        {% if request.user|check_in_group:"Admin" %}
            <img src="/media/user_groups/admin.png" alt="admin" width="20" height="20" style="margin-left: 5px;">
        {% endif %}
    </a>

    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'users:profile' pk=request.user.id %}">Profile</a></li>
        <li><a class="dropdown-item" href="{% url 'direct:messages' %}">Messages</a></li>
        <li><a class="dropdown-item" href="{% url 'users:user_ideas' pk=request.user.id %}">Ideas</a></li>
        <li><a class="dropdown-item" href="{% url 'users:followers' pk=request.user.id %}">Followers</a></li>
        <li><a class="dropdown-item" href="{% url 'users:partnerships' pk=request.user.id %}">Partnerships</a></li>
        <li><a class="dropdown-item" href="{% url 'users:investments' pk=request.user.id %}">Investments</a></li>
        <li><a class="dropdown-item" href="{% url 'users:favourites' pk=request.user.id %}">Favourite Ideas</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{% url 'notifications:show-notifications' %}">Notifications&Requests</a></li>

    </ul>


</li>